### ISSUE TITLE
Feature: Support self-hosted Windows runner for Github Enterprise Server (GHES)

### ISSUE THREAD

**Issue by oldking139** [fortytwoservices/terraform-azurerm-selfhostedrunnervmss#115]
### Background
- Right now, as I check from the documentation: [Step 2 - Configuring the virtual machine scale set for auto registration](https://docs.fortytwo.io/marketplace-offerings/self-hosted-runners/github/step2/#configure-the-vmss-to-auto-register-new), We only can generate a new PAT on github.com and connect our VMSS to github.com, no info mentioned for GHES.
- But for some company (like us), we need self-hosted Github enterprise server instance (as known as [GHES](https://docs.github.com/en/enterprise-server@3.12/admin/overview/about-github-enterprise-server)), which is almost same as github.com(also same [Github api version](https://docs.github.com/en/enterprise-server@3.12/rest/about-the-rest-api/api-versions?apiVersion=2022-11-28)) except with different domain name(DNS). And as from docs of Github, they does not support GHES using Github's hosted runner.
- So far the Linux self-hosted runner is tending to mature deployment architecture, but for Windows, still not quite handy to get a easy way to auto-scaling and auto register/connect to GHES.

### Our proposals
- We deploying and using self-hosted Windows runners as org level, not enterprise level (or instance level in GHES).
- We hope the script using to auto register can add a new option flag, that we can specify our GHES url, e.g `GH_API_URL=api.githubserver.my` and then use `-githubapi $GHE_API_URL` as a flag.
- And for ease-of-use, when this value is blank, using default github.com API endpoint.
- As the API version of github.com and GHES are the same, I think there is not much work to do for this feature😉.

**Comment by oldking139** [comment]
Never mind, I found this in script:
https://github.com/fortytwoservices/terraform-azurerm-selfhostedrunnervmss/blob/3255abb0390f5334b8c3d9e1cdd0de2b8e2127e6/scripts/script.sh#L94

But the documentation did not updated.

**Comment by mysteq** [comment]
Hi!
We're adding a parameter for githubhostname in the Windows powershell onboarding script then.
As you mention, it should work even for GHES, but we don't have such server available for us, so I can't actually test that it is working.

**Comment by oldking139** [comment]
I have tested the new powershell script, and I can confirm this change works alright.
