### ISSUE TITLE
Feature / Question: GitHub Runners at the Enterprise Level

### ISSUE THREAD

**Issue by tim-chaffin** [fortytwoservices/terraform-azurerm-selfhostedrunnervmss#54]
I've been able to add GitHub runners at an org level, and this works as expected.

Is there anyway to add the virtual machine scale set, as self-hosted runners at the Enterprise level? If that functionality already exists, how would I do that?

**Comment by mysteq** [comment]
Hi!
Currently we have not implemented functionality for that. Enterprise level hasn't been a use case for us so far, and we would need to look into what is needed for that.

**Comment by tlchaffi** [comment]
Just checking in and poking the issue, to ensure its not auto-closed.

**Comment by mysteq** [comment]
I have some code for this, which I expect should work based on documentation.
However I don't currently have an Enterprise available for testing this on, so it's currently not moved into the documented script.

So it would work with specifying the first argument as "enterprises/<enterprise>". At least that is the idea :)

Currently it's located here until I can verify it's working:
https://github.com/amestofortytwo/terraform-azurerm-selfhostedrunnervmss/blob/main/scripts/script_preview_v2.sh

**Comment by mysteq** [comment]
Since it doesn't break anything the changes for this has also moved it to the regular script, however we still don't have access to an Enterprise to verify, so it's going to be a bit of an experimental feature still.
